include:
  - local: '.gitlab-ci-template.yml'
  - project: clops/gitlab-ci-pop-analysis
    ref: master
    file: pop_analysis.yaml
  - project: releng/common-gitlab-ci
    ref: master
    file: sbom-generate.yml
  - project: altair/altair-build-common
    ref: master
    file: gitlab/ci/altair_versioning.yml
  - project: altair/altair-build-common
    ref: master
    file: gitlab/ci/altair_common.yml

# List of job stages in their order of execution.
stages:
  - build
  - contract_test
  - coverage_report
#  - Check_dist
#  - changelog
  - analysis
  - sbom
  - notification


variables:
  BUILD_TOOL: npm
  GIT_DEPTH: 10
  BD_PRODUCT_GROUP: PolarisNG Projects Group
  BD_VERSION_PHASE: DEVELOPMENT
  DISABLE_POLARIS_CLASSIC_ANALYSIS: "true"

##### MERGE REQUEST PIPELINE #####

build_unit_test_job:
  extends:
    - .build_unit_tests
  stage: build

contract_test_job:
  extends:
    - .contract_tests
  stage: build

code_coverage_job:
  stage: coverage_report
  extends:
    -  .code_coverage

#check_dist_job:
#  extends:
#    - .check_dist
#  stage: Check_dist

.export_sbom_variables:
  before_script:
    - export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - export ARTIFACTORY_UPLOAD_REPO=1
    - export SBOM_ART_TOKEN_VAULT_PATH=sbom/integrations/github-actions
    - export PRODUCT=Integrations
    - export GENERATE_CONFIGURATION_FILE=1
    - export GENERATION_OPTIONS="--entry integrations/mirrored-repos/synopsys-action-ci-cd:synopsys-action-ci-cd-$PACKAGE_VERSION"
    - export PRODUCT_ADDON_SBOM_OPTIONS="--output-zipfile synopsys-action-ci-cd-$PACKAGE_VERSION.zip"

generate_sbom:
  extends:
    - .export_sbom_variables
    - .run_sbom_generation
  stage: sbom
  only:
    refs:
      - main

polaris_bridge:
  stage: analysis
  extends: .polaris_bridge

pop_blackduck:
  image: us-docker.pkg.dev/cloudops-artifacts-prd/polaris/ember_cli:3.28.5-node_16
  extends:
    - .new_pop_blackduck
  before_script:
    - |
      apt-get update -y
      apt-get install -y rsync make jq python3 python3-pip
      pip3 install blackduck requests
      export RELEASE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')

#changelog_job:
#  extends:
#    - .changelog
#    - .only
#  stage: changelog
